name: test-and-publish-package

on:
  workflow_call:
    inputs:
      # optional
      install-eplus-2210:
        description: Should I install Energy Plus 22.1.0 ?
        required: false
        type: boolean

      python-conda-requirement:
        description: Specific python requirement to install with conda (for example "=3.7.0" or ">=3.7,<3.8") ?
        required: false
        type: string
        default: ">=3.8"

      python-pip-requirement:
        description: Specific python requirement to install with pip (for example "=3.7.0" or ">=3.7,<3.8") ?
        required: false
        type: string
        default: ">=3.8"

      publish-to-pypi:
        description: Should I publish to Pypi ? (! only for public packages !)
        required: false
        type: boolean
        default: false

      # documentation testing only, a doc build is triggered by readthedocs when pushed on master
      check-documentation:
        description: Should I check that documentation generates correctly?
        required: false
        type: boolean
        default: false

      # tests can be executed on different os (ubuntu, linux, macos), different python versions
      os-requirements:
        description: OS requirements
        required: false
        type: string
        default: "['ubuntu-latest']"

      python-test-versions:
        description: Python versions to be tested
        required: false
        type: string
        default: "['3.12']"

    secrets:
      # mandatory
      ADMIN_GITHUB_TOKEN:
        description: Openergy admin github token
        required: true
      AZURE_CONDA_CHANNEL_KEY:
        description: Azure Storage Account key
        required: true

      # optional
      CONDA_CHANNEL_SYSADMIN_URL:
        description: URL containing sysadmin password to use Openergy's private conda channel.
        required: false
      PYPI_API_TOKEN:
        description: openergy's pypi api token (only if publish to pypi)
        required: false

jobs:
  conda-build:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.build-package.outputs.build-version }}
    steps:
      - name: build package
        id: build-package
        uses: openergy/ogithub-actions/actions/opypackage-conda-build-v05@master
        with:
          python-requirement: ${{ inputs.python-conda-requirement }}
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}

  conda-test:
    needs: [conda-build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os-requirements) }}
        python-version: ${{ fromJson(inputs.python-test-versions) }}
    steps:
      - name: test package
        uses: openergy/ogithub-actions/actions/opypackage-conda-test-v03@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          python-requirement: ${{ inputs.python-conda-requirement }}
          python-version: ${{  matrix.python-version }}
          build-version: ${{ needs.conda-build.outputs.build-version }}
          conda-channel-sysadmin-url: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
          install-eplus-2210: ${{ inputs.install-eplus-2210 }}
          check-documentation: ${{ inputs.check-documentation}}

  version:
    needs: [conda-build, conda-test]
    runs-on: ubuntu-latest
    if: needs.conda-build.outputs.build-version != 'next'
    steps:
      - name: version repo
        uses: openergy/ogithub-actions/actions/opy-version-v01@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          build-version: ${{ needs.conda-build.outputs.build-version }}

  pypi-publish:
    needs: [conda-build, conda-test, version]
    runs-on: ubuntu-latest
    if: ${{ inputs.publish-to-pypi }}
    steps:
      - name: publish package to pypi
        uses: openergy/ogithub-actions/actions/opypackage-pip-build-and-publish-v02@master
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          pypi-openergy-token: ${{ secrets.PYPI_API_TOKEN }}
          python-requirement: ${{ inputs.python-pip-requirement }}
          build-version: ${{ needs.conda-build.outputs.build-version }}

  conda-publish:
    needs: [conda-build, conda-test, version]
    runs-on: ubuntu-latest
    steps:
      - name: publish package to private conda registry
        uses: openergy/ogithub-actions/actions/opypackage-conda-publish-v02@master
        with:
          azure-conda-channel-key: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
